version: "3.9"

services:
  summarizer:
    container_name: linkedin-summarizer
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    env_file: ./backend/.env
    ports:
      - "8085:8085"
